services:
  - type: web
    name: arquivo-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    branch: main
    runtime: python
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
